Repository 6regorio/practicasEnero2021, pull requests merged in 2021-01, with the labels that each got.

#1 Realizados Test
  src/test/java/zz210120/Gre.xml
  target/classes/.gitignore
  target/classes/META-INF/maven/cenec/selenium/pom.properties
  target/test-classes/.gitignore
  target/test-classes/zz210120/Gre.xml
  test-output/Conjunto de todas las pruebas/Pruebas con identificacion necesaria.html
  test-output/Conjunto de todas las pruebas/Pruebas con identificacion necesaria.xml
  test-output/Conjunto de todas las pruebas/Pruebas sin identificacion.html
  test-output/Conjunto de todas las pruebas/Pruebas sin identificacion.xml
  test-output/Conjunto de todas las pruebas/testng-failed.xml
  test-output/emailable-report.html
  test-output/index.html
  test-output/junitreports/TEST-zz210120.AbrirCoronavirus.xml
  test-output/junitreports/TEST-zz210120.CargaNotificacionesY3Mas.xml
  test-output/junitreports/TEST-zz210120.ComprobarCarpetaSalud6Links.xml
  test-output/junitreports/TEST-zz210120.EncontrarFarmaciaConFecha.xml
  test-output/junitreports/TEST-zz210120.IniciarSesionDniElectronico.xml
  test-output/junitreports/TEST-zz210120.MiPerfilPrivado.xml
  test-output/junitreports/TEST-zz210120.PedirCita2Links.xml
  test-output/junitreports/TEST-zz210120.TelefonoPopUp.xml
  test-output/old/Conjunto de todas las pruebas/methods-alphabetical.html
  test-output/old/Conjunto de todas las pruebas/methods.html
  test-output/old/Conjunto de todas las pruebas/toc.html
  test-output/old/index.html
  test-output/testng-failed.xml
  test-output/testng-results.xml
Labels: duplicate

#4 Simple Modificación Comentario
  PruebasCargaJMeter/.classpath
  PruebasFuncionalesSelenium/src/test/java/zz210120/MiPerfilPrivado.java
  PruebasFuncionalesSelenium/target/classes/.gitignore
  PruebasFuncionalesSelenium/target/classes/META-INF/MANIFEST.MF
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.properties
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.xml
Labels: question

#5 Activar Test Logout y Lista de espera
  PruebasFuncionalesSelenium/.settings/org.eclipse.core.resources.prefs
  PruebasFuncionalesSelenium/src/test/java/privado/ComprobarCarpetaSalud6Links.java
  PruebasFuncionalesSelenium/src/test/java/privado/IniciarSesionDniElectronico.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivado.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivadoLogOut.java
  PruebasFuncionalesSelenium/src/test/java/publico/AbrirCoronavirus.java
  PruebasFuncionalesSelenium/src/test/java/publico/CargaNotificacionesY3Mas.java
  PruebasFuncionalesSelenium/src/test/java/publico/EncontrarFarmaciaConFecha.java
  PruebasFuncionalesSelenium/src/test/java/publico/EncontrarFarmaciaDataProvider.java
  PruebasFuncionalesSelenium/src/test/java/publico/PedirCita2Links.java
  PruebasFuncionalesSelenium/src/test/java/publico/TelefonoPopUp.java
  PruebasFuncionalesSelenium/src/test/java/testngFull.xml
  PruebasFuncionalesSelenium/src/test/java/zz210120/testng.xml
  PruebasFuncionalesSelenium/src/test/java/zz210120/testngFull.xml
  PruebasFuncionalesSelenium/target/classes/.gitignore
  PruebasFuncionalesSelenium/target/classes/META-INF/MANIFEST.MF
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.properties
  PruebasFuncionalesSelenium/target/test-classes/.gitignore
  PruebasFuncionalesSelenium/target/test-classes/zz210120/testng.xml
  PruebasFuncionalesSelenium/target/test-classes/zz210120/testngFull.xml
Labels: bug

#6 conClavePermanente
  PruebasFuncionalesSelenium/.classpath
  PruebasFuncionalesSelenium/.gitignore
  PruebasFuncionalesSelenium/.settings/org.eclipse.core.resources.prefs
  PruebasFuncionalesSelenium/pom.xml
  PruebasFuncionalesSelenium/src/test/java/privado/ComprobarCarpetaSalud6Links.java
  PruebasFuncionalesSelenium/src/test/java/privado/IniciarSesionDniElectronico.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivado.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivadoLogOut.java
  PruebasFuncionalesSelenium/src/test/java/publico/AbrirCoronavirus.java
  PruebasFuncionalesSelenium/src/test/java/publico/EncontrarFarmaciaConFecha.java
  PruebasFuncionalesSelenium/src/test/java/publico/EncontrarFarmaciaDataProvider.java
  PruebasFuncionalesSelenium/src/test/resources/firefoxdriver/geckodriver.exe
  PruebasFuncionalesSelenium/target/classes/.gitignore
  PruebasFuncionalesSelenium/target/classes/META-INF/MANIFEST.MF
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.properties
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.xml
  PruebasFuncionalesSelenium/target/test-classes/.gitignore
Labels: enhancement

#7 Permite elegir autenticación DNIe o Clave Permanenete
  PruebasFuncionalesSelenium/src/test/java/privado/ComprobarCarpetaSalud6Links.java
  PruebasFuncionalesSelenium/src/test/java/privado/IniciarSesionDniElectronico.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivado.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivadoLogOut.java
  PruebasFuncionalesSelenium/src/test/java/publico/AbrirCoronavirus.java
  PruebasFuncionalesSelenium/src/test/java/publico/CargaNotificacionesY3Mas.java
  PruebasFuncionalesSelenium/src/test/java/publico/EncontrarFarmaciaConFecha.java
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.properties
Labels: enhancement

#8 Funcionando OK
  PruebasFuncionalesSelenium/.settings/org.eclipse.core.resources.prefs
  PruebasFuncionalesSelenium/src/test/java/privado/AutenticacionRequerida.java
  PruebasFuncionalesSelenium/src/test/java/privado/ComprobarCarpetaSalud6Links.java
  PruebasFuncionalesSelenium/src/test/java/privado/IniciarSesionDniElectronico.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivado.java
  PruebasFuncionalesSelenium/src/test/java/privado/MiPerfilPrivadoLogOut.java
  PruebasFuncionalesSelenium/src/test/java/publico/AbrirCoronavirus.java
  PruebasFuncionalesSelenium/src/test/java/publico/CargaNotificacionesY3Mas.java
  PruebasFuncionalesSelenium/src/test/java/publico/EncontrarFarmaciaConFecha.java
  PruebasFuncionalesSelenium/src/test/java/publico/PedirCita2Links.java
  PruebasFuncionalesSelenium/src/test/java/publico/SinAutenticar.java
  PruebasFuncionalesSelenium/src/test/java/publico/TelefonoPopUp.java
  PruebasFuncionalesSelenium/src/test/java/test.xml
  PruebasFuncionalesSelenium/src/test/java/testngFull.xml
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.properties
Labels: enhancement

#9 Añadidos comentarios a las funciones
  PruebasFuncionalesSelenium/pom.xml
  PruebasFuncionalesSelenium/src/test/java/privado/AutenticacionRequerida.java
  PruebasFuncionalesSelenium/src/test/java/publico/SinAutenticar.java
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.properties
  PruebasFuncionalesSelenium/target/classes/META-INF/maven/funcionales/PruebasFuncionalesSelenium/pom.xml
  SeleniumHilos/src/test/java/publico/ComprobarClickTelefonoHilos.java
  SeleniumHilos/src/test/java/publico/MiHilo.java
  SeleniumHilos/src/test/java/publico/SinAutenticar.java
Labels: documentation
